server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Dùng cho React Router để không bị lỗi 404 khi load trực tiếp link
        try_files $uri $uri/ /index.html;
    }
}
