version: '3.8'

services:
  # 1. Container cho Database MySQL
  db:
    image: mysql:8.0
    container_name: movieflix_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 18004huyhio # Mật khẩu root theo file .env của bạn
      MYSQL_DATABASE: movieflix_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. Container cho Backend NodeJS
  backend:
    build: ./Backend
    container_name: movieflix_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=18004huyhio
      - DB_NAME=movieflix_db
      - JWT_SECRET=movieflix_super_secret_key_2024
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db

  # 3. Container cho Frontend (React/Vite)
  frontend:
    build: ./frontend
    container_name: movieflix_frontend
    restart: always
    ports:
      - "3000:80" # Ánh xạ cổng 3000 của host với cổng 80 của container Nginx
    depends_on:
      - backend

volumes:
  db_data:
